# Generated by Django 4.0.3 on 2022-05-03 21:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameLobby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word_1', models.CharField(max_length=5)),
                ('word_2', models.CharField(max_length=5)),
                ('GameStatus', models.BooleanField(default=True)),
                ('Player_1_Status', models.BooleanField(default=False)),
                ('Player_2_Status', models.BooleanField(default=False)),
                ('Player_1', models.ManyToManyField(related_name='player_1', to=settings.AUTH_USER_MODEL)),
                ('Player_2', models.ManyToManyField(related_name='player_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.ManyToManyField(related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ManyToManyField(related_name='sender', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
