# Generated by Django 4.0.3 on 2022-05-03 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameinvite',
            name='receiver',
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='gameinvite',
            name='sender',
        ),
        migrations.AddField(
            model_name='gameinvite',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to=settings.AUTH_USER_MODEL),
        ),
    ]
