# Generated by Django 4.0.3 on 2022-05-04 10:31

import Game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_remove_gameinvite_receiver_gameinvite_receiver_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelobby',
            name='word_1',
            field=models.CharField(default=Game.models.random_word, max_length=5),
        ),
        migrations.AlterField(
            model_name='gamelobby',
            name='word_2',
            field=models.CharField(default=Game.models.random_word, max_length=5),
        ),
    ]
