# Generated by Django 4.0.3 on 2022-05-05 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Game', '0003_alter_gamelobby_word_1_alter_gamelobby_word_2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelobby',
            old_name='Player_1_Status',
            new_name='GameFinished',
        ),
        migrations.RenameField(
            model_name='gamelobby',
            old_name='Player_2_Status',
            new_name='Player_1_Finished',
        ),
        migrations.RemoveField(
            model_name='gamelobby',
            name='GameStatus',
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='Player_1_Move',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='Player_2_Finished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='Player_2_Move',
            field=models.IntegerField(blank=True, default=6),
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='game_invite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Game.gameinvite'),
        ),
        migrations.RemoveField(
            model_name='gamelobby',
            name='Player_1',
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='Player_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='gamelobby',
            name='Player_2',
        ),
        migrations.AddField(
            model_name='gamelobby',
            name='Player_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_2', to=settings.AUTH_USER_MODEL),
        ),
    ]
