# Generated by Django 4.0.4 on 2022-05-05 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0005_gameinvite_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamelobby',
            old_name='Player_1_Move',
            new_name='Player_1_Moves',
        ),
        migrations.RenameField(
            model_name='gamelobby',
            old_name='Player_2_Move',
            new_name='Player_2_Moves',
        ),
    ]
